### ISSUE TITLE
Linker: a typo when returning a result in ReadName()

### ISSUE THREAD

**Issue by Oleg-N-Cher** [ogdenpm/intel80tools#2]
In the file c-ports/link/link3.c

```
byte ReadName()
{
	ChkRead(1);		/* make sure 1 char there */
	inP = bufP;			/* set to start of name */
	if (recLen < 2)		/* only CRC left ? */
	{
		bufP = bufP + recLen;	/* advance and flag no more */
		return (byte)recLen = 0;
		^^^^^^^^^^^^^^^^^^^^^^^^
	}
```

`return (byte)recLen = 0;` will always return 0. I suppose the line should look like this.

`return (byte)recLen == 0;`

**Comment by Oleg-N-Cher** [comment]
Perhaps I not quite rights about ==, but GCC clearly not likes this line:

![link](https://user-images.githubusercontent.com/1090608/65362052-aeb10380-dc0e-11e9-9e09-65f951957821.png)

**Comment by ogdenpm** [comment]
Oleg
I realise I hadn't formally closed this. The code was fixed a while ago to be (byte)(recLen = 0)
